Class {
	#name : 'TFAttributeName',
	#superclass : 'Object',
	#category : 'TensorFlowOperationMathModel'
}

{ #category : 'Accessing' }
TFAttributeName class >> container [

	^'container'
]

{ #category : 'Accessing' }
TFAttributeName class >> dataType [

	^'dtype' 
]

{ #category : 'Accessing' }
TFAttributeName class >> outputShapes [

	^'output_shapes'
]

{ #category : 'Accessing' }
TFAttributeName class >> outputTypes [

	^'output_types'
]

{ #category : 'Accessing' }
TFAttributeName class >> shape [

	^'shape'
]

{ #category : 'Accessing' }
TFAttributeName class >> sharedName [

	^'shared_name'
]

{ #category : 'Accessing' }
TFAttributeName class >> transposeA [

	^'transpose_a'
]

{ #category : 'Accessing' }
TFAttributeName class >> transposeB [

	^'transpose_b'
]

{ #category : 'Accessing' }
TFAttributeName class >> useNesterov [

	^'use_nesterov'
]

{ #category : 'Accessing' }
TFAttributeName class >> value [

	^'value' 
]
